### ISSUE TITLE
Mail merge broken in version 2.14

### ISSUE THREAD

**Issue by agoddard77** [tbar0970/jethro-pmm#150] opened 2016-03-01 00:02 UTC
The function to mail-merge a document is to be broken in 2.14. When I try to, here is the error message I get:

Fatal error: Class 'Custom_Field' not found in /home/christch/public_html/jethro/db_objects/person.class.php on line 210

The easyjethro demo version gets the exact same message, so I know it's not just me:

Fatal error: Class 'Custom_Field' not found in /home/eaea6621/public_html/demo/db_objects/person.class.php on line 210

Thanks for your help! Andrew.

**Comment by tbar0970** [comment] 2016-03-01 00:49
Duplicate of Issue #147 which has a fix coming in the next minor release.

**Closed by tbar0970** 2016-03-01 00:49 UTC
Labels: duplicate
