### ISSUE TITLE
Error attempting to delete an empty congregation

### ISSUE THREAD

**Issue by s4069b** [tbar0970/jethro-pmm#687] opened 2021-01-11 02:40 UTC
I did a quick search and can't see anyone else reporting this. 

---------------
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`jethro`.`account_congregation_restriction`, CONSTRAINT `account_group_restriction_congregationid` FOREIGN KEY (`congregationid`) REFERENCES `congregation` (`id`)) 
Line 440 of /var/www/......../include/db_object.class.php

USER:       1 
REFERER:    https://......../?view=admin__congregations
USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15

REQUEST: 
Array
(
   [view] => admin__congregations
   [action] => delete
   [congregationid] => 8
)

BACKTRACE:
Array
(
   [0] => Array
       (
           [file] => /var/www/......../include/db_object.class.php
           [line] => 440
           [function] => query
           [class] => PDO
           [type] => ->
       )

**Comment by tbar0970** [comment] 2021-01-12 10:56
Looks like a duplicate of issue #663.
The workaround is to find the users who are restricted to that congregation and adjust them accordingly.

**Closed by tbar0970** 2021-01-12 10:56 UTC

**Comment by s4069b** [comment] 2021-01-13 02:05
I don't have any users restricted to the Congregation that I want to delete, so I thought it may be different to #663

**Comment by s4069b** [comment] 2021-01-13 02:07
OOPS. Take that back. 
I had to reveal 'inactive users' to find the user who had that Congregation in their restricted access. 
Wow... that was sneaky. 
And YES you are correct, the Congregation is now able to be deleted, so it's the same as #663.
