### ISSUE TITLE
Other tallies for attendance

### ISSUE THREAD

**Issue by tim-pearce** [tbar0970/jethro-pmm#912] opened 2023-06-14 00:30 UTC
It's nice that we have a field for head count but I would like some others of a similar nature. This would need to be a user defined set.
In our case we have, in addition to the 'named' attenders
- other visitors (whose names we don't know or who are unlikely to become regulars)
- children
- communicants
Currently I generate a document and then have to fill these values in manually in the document.

**Comment by tbar0970** [comment] 2023-06-14 01:49
Duplicate of #200

**Closed by tbar0970** 2023-06-14 01:49 UTC
