### ISSUE TITLE
Error: Undefined view when you cancel an edit via the member interface

### ISSUE THREAD

**Issue by ken-h** [tbar0970/jethro-pmm#69] opened 2015-07-20 02:29 UTC
v2.11.
Click on Edit to edit family details once in the member interface, but then click Cancel.  Result is Error: Undefined view

**Comment by edwhiting** [comment] 2015-09-05 00:33
What are the exact steps to reproduce this?
I am unable to reproduce this in v2.12; it may have been fixed in that version.

Regards,
Edward

**Comment by ken-h** [comment] 2015-09-07 05:00
I haven't tried on v2.12, but the exact steps in v2.11 are as stated in my original post.

**Closed** 2015-09-11 09:51 UTC
Labels: bug, severity-medium
